# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 400)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.btnNewSession = QtWidgets.QPushButton(self.centralWidget)
        self.btnNewSession.setGeometry(QtCore.QRect(10, 0, 71, 71))
        self.btnNewSession.setObjectName("btnNewSession")
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(590, 150, 301, 191))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.btnScanPulseA = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnScanPulseA.setFont(font)
        self.btnScanPulseA.setObjectName("btnScanPulseA")
        self.gridLayout_2.addWidget(self.btnScanPulseA, 6, 0, 1, 2)
        self.intMaxPulseC = QtWidgets.QSpinBox(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intMaxPulseC.sizePolicy().hasHeightForWidth())
        self.intMaxPulseC.setSizePolicy(sizePolicy)
        self.intMaxPulseC.setMaximum(4000)
        self.intMaxPulseC.setObjectName("intMaxPulseC")
        self.gridLayout_2.addWidget(self.intMaxPulseC, 5, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.intDeadTimeAC = QtWidgets.QSpinBox(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intDeadTimeAC.sizePolicy().hasHeightForWidth())
        self.intDeadTimeAC.setSizePolicy(sizePolicy)
        self.intDeadTimeAC.setMaximum(4000)
        self.intDeadTimeAC.setObjectName("intDeadTimeAC")
        self.gridLayout_2.addWidget(self.intDeadTimeAC, 2, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 2, 0, 1, 1)
        self.intMinPulseA = QtWidgets.QSpinBox(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intMinPulseA.sizePolicy().hasHeightForWidth())
        self.intMinPulseA.setSizePolicy(sizePolicy)
        self.intMinPulseA.setMinimum(1)
        self.intMinPulseA.setMaximum(55)
        self.intMinPulseA.setObjectName("intMinPulseA")
        self.gridLayout_2.addWidget(self.intMinPulseA, 1, 1, 1, 1)
        self.intMaxPulseA = QtWidgets.QSpinBox(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intMaxPulseA.sizePolicy().hasHeightForWidth())
        self.intMaxPulseA.setSizePolicy(sizePolicy)
        self.intMaxPulseA.setMinimum(1)
        self.intMaxPulseA.setMaximum(55)
        self.intMaxPulseA.setObjectName("intMaxPulseA")
        self.gridLayout_2.addWidget(self.intMaxPulseA, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 5, 0, 1, 1)
        self.layoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 210, 191, 130))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.intMaxVoltage = QtWidgets.QSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intMaxVoltage.sizePolicy().hasHeightForWidth())
        self.intMaxVoltage.setSizePolicy(sizePolicy)
        self.intMaxVoltage.setMinimum(1)
        self.intMaxVoltage.setMaximum(55)
        self.intMaxVoltage.setObjectName("intMaxVoltage")
        self.gridLayout_3.addWidget(self.intMaxVoltage, 2, 1, 1, 1)
        self.intMinVoltage = QtWidgets.QSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intMinVoltage.sizePolicy().hasHeightForWidth())
        self.intMinVoltage.setSizePolicy(sizePolicy)
        self.intMinVoltage.setMinimum(1)
        self.intMinVoltage.setMaximum(55)
        self.intMinVoltage.setObjectName("intMinVoltage")
        self.gridLayout_3.addWidget(self.intMinVoltage, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 3, 0, 1, 1)
        self.btnScanV = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnScanV.setFont(font)
        self.btnScanV.setObjectName("btnScanV")
        self.gridLayout_3.addWidget(self.btnScanV, 5, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.dblVoltSec = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.dblVoltSec.setObjectName("dblVoltSec")
        self.gridLayout_3.addWidget(self.dblVoltSec, 1, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(210, 210, 181, 131))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setHorizontalSpacing(6)
        self.gridLayout_4.setVerticalSpacing(4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 1)
        self.dblVoltSec_2 = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.dblVoltSec_2.setObjectName("dblVoltSec_2")
        self.gridLayout_4.addWidget(self.dblVoltSec_2, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 1, 0, 1, 1)
        self.intMaxCurrent = QtWidgets.QSpinBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intMaxCurrent.sizePolicy().hasHeightForWidth())
        self.intMaxCurrent.setSizePolicy(sizePolicy)
        self.intMaxCurrent.setMaximum(4000)
        self.intMaxCurrent.setObjectName("intMaxCurrent")
        self.gridLayout_4.addWidget(self.intMaxCurrent, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 2, 0, 1, 1)
        self.intMinCurrent = QtWidgets.QSpinBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intMinCurrent.sizePolicy().hasHeightForWidth())
        self.intMinCurrent.setSizePolicy(sizePolicy)
        self.intMinCurrent.setMaximum(4000)
        self.intMinCurrent.setObjectName("intMinCurrent")
        self.gridLayout_4.addWidget(self.intMinCurrent, 2, 1, 1, 1)
        self.btnScanI = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnScanI.setFont(font)
        self.btnScanI.setObjectName("btnScanI")
        self.gridLayout_4.addWidget(self.btnScanI, 3, 0, 1, 2)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(400, 270, 181, 71))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.btnRun = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnRun.setFont(font)
        self.btnRun.setObjectName("btnRun")
        self.gridLayout.addWidget(self.btnRun, 1, 0, 1, 2)
        self.intMilligrams = QtWidgets.QSpinBox(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intMilligrams.sizePolicy().hasHeightForWidth())
        self.intMilligrams.setSizePolicy(sizePolicy)
        self.intMilligrams.setMaximum(4000)
        self.intMilligrams.setObjectName("intMilligrams")
        self.gridLayout.addWidget(self.intMilligrams, 0, 1, 1, 1)
        self.btnGraphVIT = QtWidgets.QPushButton(self.centralWidget)
        self.btnGraphVIT.setGeometry(QtCore.QRect(440, 0, 71, 71))
        self.btnGraphVIT.setObjectName("btnGraphVIT")
        self.btnGraphVI = QtWidgets.QPushButton(self.centralWidget)
        self.btnGraphVI.setGeometry(QtCore.QRect(530, 0, 71, 71))
        self.btnGraphVI.setObjectName("btnGraphVI")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnNewSession.setText(_translate("MainWindow", "NEW \n"
" SESSION"))
        self.label_10.setText(_translate("MainWindow", "MAX PULSE WIDTH"))
        self.btnScanPulseA.setText(_translate("MainWindow", "SCAN_ANODIC_PULSE"))
        self.label_3.setText(_translate("MainWindow", "MIN PULSE WIDTH"))
        self.label_14.setText(_translate("MainWindow", "DEAD_TIME"))
        self.label_15.setText(_translate("MainWindow", "CATHODE PULSE"))
        self.label_4.setText(_translate("MainWindow", "VOLTAGE MAX"))
        self.label_2.setText(_translate("MainWindow", "VOLTAGE MIN"))
        self.btnScanV.setText(_translate("MainWindow", "SCAN_V"))
        self.label_7.setText(_translate("MainWindow", "Volts/Sec"))
        self.label_9.setText(_translate("MainWindow", "mA/Sec"))
        self.label_5.setText(_translate("MainWindow", "CURRENT MAX"))
        self.label_6.setText(_translate("MainWindow", "CURRENT MIN"))
        self.btnScanI.setText(_translate("MainWindow", "SCAN_I"))
        self.label_8.setText(_translate("MainWindow", "mg to Transfer"))
        self.btnRun.setText(_translate("MainWindow", "DC_RUN"))
        self.btnGraphVIT.setText(_translate("MainWindow", "GRAPH \n"
" VI-Time"))
        self.btnGraphVI.setText(_translate("MainWindow", "GRAPH \n"
" V vs I"))

