# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 400)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.btnNewSession = QtWidgets.QPushButton(self.centralWidget)
        self.btnNewSession.setGeometry(QtCore.QRect(10, 0, 71, 71))
        self.btnNewSession.setObjectName("btnNewSession")
        self.btnScanV = QtWidgets.QPushButton(self.centralWidget)
        self.btnScanV.setGeometry(QtCore.QRect(940, 260, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnScanV.setFont(font)
        self.btnScanV.setObjectName("btnScanV")
        self.btnRun = QtWidgets.QPushButton(self.centralWidget)
        self.btnRun.setGeometry(QtCore.QRect(700, 260, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnRun.setFont(font)
        self.btnRun.setObjectName("btnRun")
        self.layoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(700, 10, 311, 241))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.intMinVoltage = QtWidgets.QSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intMinVoltage.sizePolicy().hasHeightForWidth())
        self.intMinVoltage.setSizePolicy(sizePolicy)
        self.intMinVoltage.setMinimum(1)
        self.intMinVoltage.setMaximum(55)
        self.intMinVoltage.setObjectName("intMinVoltage")
        self.gridLayout_2.addWidget(self.intMinVoltage, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.intMinCurrent = QtWidgets.QSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intMinCurrent.sizePolicy().hasHeightForWidth())
        self.intMinCurrent.setSizePolicy(sizePolicy)
        self.intMinCurrent.setMaximum(4000)
        self.intMinCurrent.setObjectName("intMinCurrent")
        self.gridLayout_2.addWidget(self.intMinCurrent, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.intMaxCurrent = QtWidgets.QSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intMaxCurrent.sizePolicy().hasHeightForWidth())
        self.intMaxCurrent.setSizePolicy(sizePolicy)
        self.intMaxCurrent.setMaximum(4000)
        self.intMaxCurrent.setObjectName("intMaxCurrent")
        self.gridLayout_2.addWidget(self.intMaxCurrent, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.intMaxVoltage = QtWidgets.QSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intMaxVoltage.sizePolicy().hasHeightForWidth())
        self.intMaxVoltage.setSizePolicy(sizePolicy)
        self.intMaxVoltage.setMinimum(1)
        self.intMaxVoltage.setMaximum(55)
        self.intMaxVoltage.setObjectName("intMaxVoltage")
        self.gridLayout_2.addWidget(self.intMaxVoltage, 0, 1, 1, 1)
        self.dblVoltSec = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.dblVoltSec.setGeometry(QtCore.QRect(440, 20, 151, 51))
        self.dblVoltSec.setObjectName("dblVoltSec")
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(330, 20, 152, 55))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(270, 170, 161, 55))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.intMilligrams = QtWidgets.QSpinBox(self.centralWidget)
        self.intMilligrams.setGeometry(QtCore.QRect(440, 170, 151, 55))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intMilligrams.sizePolicy().hasHeightForWidth())
        self.intMilligrams.setSizePolicy(sizePolicy)
        self.intMilligrams.setMaximum(4000)
        self.intMilligrams.setObjectName("intMilligrams")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnNewSession.setText(_translate("MainWindow", "NEW \n"
" SESSION"))
        self.btnScanV.setText(_translate("MainWindow", "SCAN"))
        self.btnRun.setText(_translate("MainWindow", "RUN"))
        self.label_5.setText(_translate("MainWindow", "CURRENT MAX"))
        self.label_2.setText(_translate("MainWindow", "VOLTAGE MIN"))
        self.label_6.setText(_translate("MainWindow", "CURRENT MIN"))
        self.label_4.setText(_translate("MainWindow", "VOLTAGE MAX"))
        self.label_7.setText(_translate("MainWindow", "Volts/Sec"))
        self.label_8.setText(_translate("MainWindow", "Milligrams to Transfer"))

